name: Finds terragrunt config changes
description: Finds paths with changes to 'terragrunt.hcl' files. Excludes paths that have a 'no-terragrunt-apply' file present.

inputs:
  github-token:
    description: GitHub auth token
    required: true
  pull-request-number:
    description: Pull request number
    required: true

outputs:
  paths:
    description: JSON array of paths
    value: ${{ steps.changes.outputs.paths }}

runs:
  using: composite
  steps: 
    - id: changes
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ inputs.pull-request-number }}/files?per_page=100"
        AUTH_HEADER="Authorization: Bearer ${{ inputs.github-token }}"

        changes=$(for d in $(curl -sH "${AUTH_HEADER}" ${URL} | jq -r '.[] | select(.status != "removed") | .filename' | grep terragrunt.hcl$ | sed 's/terragrunt.hcl//'); do
          # skip paths where no-terragrunt-apply exists
          if [ \! -f $d/no-terragrunt-apply ]; then
            echo $d
          fi
        done)

        # split to json list
        echo ::set-output name=paths::$(echo -n ${changes} | jq -Rsc 'split(" ")')
      shell: bash
