name: find-changes
description: Finds directory paths with changes to 'terragrunt.hcl' files. Excludes paths that have a 'no-terragrunt-apply' file present.

inputs:
  github-token:
    description: GitHub auth token
    required: true
  pr-number:
    description: Pull request number. Either head-commit or pr-number must be given.
    required: false
  head-commit:
    description: Head commit sha. Either head-commit or pr-number must be given.
    required: false

outputs:
  updates:
    description: JSON array of directory paths with added or modified terragrunt.hcl files
    value: ${{ steps.changes.outputs.updates }}
  deletions:
    description: JSON array of directory paths with deleted terragrunt.hcl files
    value: ${{ steps.changes.outputs.deletions }}

runs:
  using: composite
  steps:
    - id: changes
      run: |
        print_path() {
          dir=$(echo "$@" | grep terragrunt.hcl$ | sed 's/terragrunt.hcl//')
          if [ ! -z "$dir" -a ! -f "${dir}/no-terragrunt-apply" ]; then
            echo "${dir}"
          fi
        }

        if [ -n "${PR_NUMBER}" ]; then
          changed_files="$(gh api repos/{owner}/{repo}/pulls/${PR_NUMBER}/files --paginate)"
        elif [ -n "${HEAD_COMMIT}" ]; then
          changed_files="$(gh api repos/{owner}/{repo}/commits/${HEAD_COMMIT} --paginate --jq .files)"
        else
          echo "Error: Either head-commit or pr-number must be be given. Exiting."
          exit 1
        fi

        updates=$(for f in $(echo "${changed_files}" | jq -r '.[] | select(.status != "removed") | .filename'); do
          print_path "$f"
        done)

        deletions=$(for f in $(echo "${changed_files}" | jq -r '.[] | select(.status == "removed") | .filename'); do
          print_path "$f"
        done)

        # Outputs as JSON arrays
        echo "updates=$(echo -n ${updates} | jq -Rsc 'split(" ")')" >> .GITHUB_OUTPUT
        echo "deletions=$(echo -n ${deletions} | jq -Rsc 'split(" ")')" >> .GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
        HEAD_COMMIT: ${{ inputs.head-commit }}
