name: Finds terragrunt config changes
description: Finds paths with changes to 'terragrunt.hcl' files. Excludes paths that have a 'no-terragrunt-apply' file present.

inputs:
  github-token:
    description: GitHub auth token
    required: true
  pull-request-number:
    description: Pull request number
    required: true

outputs:
  paths:
    description: JSON array of paths
    value: ${{ steps.changes.outputs.paths }}

runs:
  using: composite
  steps: 
    - id: changes
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ inputs.pull-request-number }}/files?per_page=100"
        AUTH_HEADER="Authorization: Bearer ${{ inputs.github-token }}"

        print_path() {
          dir=$(echo "$@" | grep terragrunt.hcl$ | sed 's/terragrunt.hcl//')
          if [ \! -f "${dir}/no-terragrunt-apply" ]; then
            echo "${dir}"
          fi
        }

        resp=$(curl -sH "${AUTH_HEADER}" ${URL})

        updates=$(for f in $(echo "${resp}" | jq -r '.[] | select(.status != "removed") | .filename'); do
          print_path "$f"
        done)

        deletions=$(for f in $(echo "${resp}" | jq -r '.[] | select(.status == "removed") | .filename'); do
          print_path "$f"
        done)

        # split to json list
        echo ::set-output name=updates::$(echo -n ${updates} | jq -Rsc 'split(" ")')
        echo ::set-output name=deletions::$(echo -n ${deletions} | jq -Rsc 'split(" ")')
      shell: bash
