name: Asserts that terraform state is unchanged
description: Fetches saved terraform state serial and compares it to the most recent one, failing fast if there is a difference

inputs:
  pr-number:
    description: Pull request number
    required: true
  working-directory:
    description: Working directory
    required: true

runs:
  using: composite
  steps:
    - run: |
        # Fetch state serials: current from state and saved from actions artifacts
        CURRENT_STATE_SERIAL=${RUNNER_TEMP}/state-serial.cur
        ARTIFACT_NAME=$(echo ${WORKING_DIRECTORY}_${PR_NUMBER} | tr '":<>|*?\\/' .)
        SAVED_STATE_SERIAL="${RUNNER_TEMP}/state-serial"

        # Call real terraform binary to get proper output. By default setup-terraform adds a wrapper and real binary
        # is in path with name terraform-bin.
        terraform=terraform
        command -v terraform-bin &> /dev/null && terraform=terraform-bin
        terragrunt state pull --terragrunt-tfpath $terraform | jq -r .serial > ${CURRENT_STATE_SERIAL}

        echo "::debug::artifact name: ${ARTIFACT_NAME}"

        error() {
          gh pr comment ${PR_NUMBER} --body "$@"
          exit 1
        }

        tmp_archive=$(mktemp ${RUNNER_TEMP}/artifact-XXXXXXXX.zip)
        dl_url=$(gh api https://api.github.com/repos/{owner}/{repo}/actions/artifacts?per_page=100 --paginate --jq ".artifacts[] | select(.name == \"${ARTIFACT_NAME}\") | .archive_download_url")
        gh api $dl_url > $tmp_archive || error "The given terraform plan can no longer be applied because saved terraform state serial is removed from github run artifacts (by default after 90 days). Try re-running the plan or open new pr."

        unzip -od ${RUNNER_TEMP} $tmp_archive
        rm $tmp_archive

        if [ ! -f "${SAVED_STATE_SERIAL}" ]; then
          # Artifact found but content is uknown
          error "The given terraform plan can no longer be applied because saved github run artifact has unknown content. Try re-running the plan or open new pr."
        fi

        echo "::debug::current state serial: $(< ${CURRENT_STATE_SERIAL})"
        echo "::debug::saved state serial: $(< ${SAVED_STATE_SERIAL})"

        cmp ${CURRENT_STATE_SERIAL} ${SAVED_STATE_SERIAL} || error "Current terraform plan can no longer be applied because the state was changed by another operation after the plan was created. Update the pull request branch from base branch to run terraform plan again"

      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        PR_NUMBER: ${{ inputs.pr-number }}
