name: Check pull request status
description: Checks if a pull request is mergeable, posting a PR comment if this is not the case

inputs:
  github-token:
    description: GitHub auth token
    required: true
  pull-request-number:
    description: Pull request number
    required: true

outputs:
  pull-request-state:
    description: Pull requrest state
    value: ${{ steps.check.outputs.pull-request-state }}
  pull-request-mergeable-state:
    description: Pull request mergeable state
    value: ${{ steps.check.outputs.pull-request-mergeable-state }}
  pull-request-head-sha:
    description: Head SHA
    value: ${{ steps.check.outputs.pull-request-head-sha }}

runs:
  using: composite
  steps:
    - id: check
      run: |
        pr_json="$(gh api repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER)"
        mergeable_state="$(jq -r .mergeable_state <<< $pr_json)"
        state="$(jq -r .state <<< $pr_json)"
        head_sha="$(jq -r .head.sha <<< $pr_json)"

        # Post PR comment indicating it is not applyable
        if [ "$state" != "open" -o "$mergeable_state" != "clean" )) ]; then
          gh pr comment $PR_NUMBER --body "Terraform apply via PR comment is blocked. Pull request must be open and mergeable (approved and status checks passing)"
        fi
        
        echo ::set-output name=pull-request-mergeable-state::${mergeable_state}
        echo ::set-output name=pull-request-state::${state}
        echo ::set-output name=pull-request-head-sha::${head_sha}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pull-request-number }}
