name: slack-notify
description: Sends a slack notification

inputs:
  text:
    description: Message text
    required: true

runs:
  using: composite
  steps:
    - run: |
        curl -X POST -H 'Content-Type: application/json' --data '{"text":${{ toJSON(inputs.text) }}}' "$SLACK_WEBHOOK_URL"
      shell: bash
