name: slack-notify
description: Sends a slack notification

inputs:
  message:
    description: Slack message
    required: true

runs:
  using: composite
  steps:
    - run: echo curl -X POST -H 'Content-type: application/json' --data '${{ inputs.message }}' $SLACK_WEBHOOK_URL
      shell: bash
