name: slack-notify
description: Sends a slack message via webhook

inputs:
  text:
    description: Message text (free-form string)
    required: true
  format:
    description: Message format (plain_text or mrkdwn)
    default: plain_text
    required: true

runs:
  using: composite
  steps:
    - run: |
        curl -X POST -H 'Content-Type: application/json' --data '{"type":${{ toJSON(inputs.format) }},"text":${{ toJSON(inputs.text) }}}' "$SLACK_WEBHOOK_URL"
      shell: bash
