name: pr-comment
description: Adds terraform plan, apply or destroy output to a pull request comment

inputs:
  github-token:
    description: GitHub auth token
    required: true
  terraform-stdout:
    description: Terraform standard out
    required: true
  terraform-stderr:
    description: Terraform standard err
    required: true
  terraform-exit-code:
    description: Terraform exit code
    required: true
  terraform-run-type:
    description: Terraform run type, i.e. plan-for-apply, plan-for-destroy, apply-on-comment, apply-on-merge or destroy-on-merge
    required: true
  pull-request-number:
    description: Pull request number
    required: true
  working-directory:
    description: Working directory
    required: true

runs:
  using: composite
  steps:
    - id: truncate
      uses: pafcloud/truncate-string@v0.1.0
      with:
        string: ${{ inputs.terraform-stdout }}${{ inputs.terraform-stderr }}
        max-length: 65000
        message: |
          ...
          [Output truncated, see logs for complete output.]

    - run: |
        details() {
          local fmt="$1"
          local open=""
          if [ "$2" == "open" ]; then
            open=" open";
          fi

          echo "<details${open}><summary>Show output</summary>"
          echo
          echo "\`\`\`${fmt}"
          echo "$3"
          echo "\`\`\`"
          echo "</details>"
        }

        plan_msg() {
          echo "### Terraform \`plan\` ($1)"
          details terraform closed "$2"
          echo
          if [ "$3" = "plan-for-apply" ]; then
            echo "Please review the plan above, ask code owners to approve this pull request, and then run terraform apply by commenting <code>/apply</code> or merging this PR"
          else
            echo "Please review the plan above, ask code owners to approve this pull request, and then run terraform destroy by merging this PR"
          fi
        }

        failed_plan_msg() {
          echo "### Terraform \`plan\` failed ($1)"
          details text open "$2"
          echo
          echo "Please fix <code>terragrunt.hcl</code> inputs/module. Terraform plan is then automatically run again"
        }

        apply_msg() {
          echo "### Terraform \`apply\` ($1)"
          details text closed "$2"
          if [ "$3" = "apply-on-comment" ]; then
            echo
            echo "Please merge this pull request to keep Git base branch and terraform-managed resource state in sync"
          fi
        }

        failed_apply_msg() {
          echo "### Terraform \`apply\` failed ($1)"
          details text open "$2"
          echo
          echo "Please fix <code>terragrunt.hcl</code> inputs/module, and then run terraform apply again"
        }

        destroy_msg() {
          echo "### Terraform \`destroy\` ($1)"
          details text closed "$2"
        }

        failed_destroy_msg() {
          echo "### Terraform \`destroy\` failed ($1)"
          details text open "$2"
          echo
          echo "Please run terraform destroy manually (do \`git checkout $3\` to restore \`terragrunt.hcl\`)"
        }

        case "${RUN_TYPE}" in
          plan-for-apply|plan-for-destroy)
            if [ ${EXIT_CODE} -eq 0 ]; then
              MSG=$(plan_msg "${WORKING_DIRECTORY}" "${INPUT}" "${RUN_TYPE}")
            else
              MSG=$(failed_plan_msg "${WORKING_DIRECTORY}" "${INPUT}")
            fi
            ;;

          apply-on-comment|apply-on-merge)
            if [ $EXIT_CODE -eq 0 ]; then
              MSG=$(apply_msg "${WORKING_DIRECTORY}" "${INPUT}" "${RUN_TYPE}")
            else
              MSG=$(failed_apply_msg "${WORKING_DIRECTORY}" "${INPUT}")
            fi
            ;;

          destroy-on-merge)
            if [ $EXIT_CODE -eq 0 ]; then
              MSG=$(destroy_msg "${WORKING_DIRECTORY}" "${INPUT}")
            else
              auth="Authorization: Bearer ${{ inputs.github-token }}"
              pr_url="https://api.github.com/repos/${{ github.repository }}/pulls/${{ inputs.pull-request-number }}"
              pr_base_sha=$(curl -sH "$auth" "$pr_url" | jq -r .base.sha)
              MSG=$(failed_destroy_msg "${WORKING_DIRECTORY}" "${INPUT}" "${pr_base_sha}")
            fi
            ;;

          *)
            echo "ERROR: Unexpected terraform run type: ${RUN_TYPE}"
            exit 5
        esac

        gh pr comment ${PULL_REQUEST_NUMBER} --body "${MSG}"

      shell: bash
      env:
        RUN_TYPE: ${{ inputs.terraform-run-type }}
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        INPUT: ${{ steps.truncate.outputs.string }}
        EXIT_CODE: ${{ inputs.terraform-exit-code }}
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
