name: run-infracost
description: Runs infracost to get a cost estimate.

inputs:
  plan-file:
    description: Path to saved terraform plan file
    required: true

  working-directory:
    description: Working directory, in which the infracost command is run
    required: true
    default: ${{ runner.temp }}

outputs:
  output:
    description: infracost output (diff)
    value: ${{ steps.this.outputs.output }}
  summary:
    description: Short summary containing old monthly + new monthly
    value: ${{ steps.this.outputs.summary }}

runs:
  using: composite
  steps:
    - id: this
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        INFRACOST_CURRENCY: EUR
        INFRACOST_CURRENCY_FORMAT="EUR: 1.234,56€"
        PLAN_FILE: ${{ inputs.plan-file }}
      run: |
        tmp_dir="$(mktemp -d $RUNNER_TEMP/XXXXXXXXXX)"
        terragrunt show -json $PLAN_FILE > $tmp_dir/plan.json
        infracost diff --path $tmp_dir/plan.json --format=json >> $tmp_dir/infracost.json

        # generate normal output from json
        echo "output<<EOF" >> $GITHUB_OUTPUT
        infracost output --format diff --path $tmp_dir/infracost.json >> $GITHUB_OUTPUT
        echo EOF >> $GITHUB_OUTPUT

        # generate summary from json
        echo "summary=$(jq -r '.projects | .[] | " \(.pastBreakdown.totalMonthlyCost) → \(.breakdown.totalMonthlyCost)"' < $tmp_dir/infracost.json) €/Month" >> $GITHUB_OUTPUT


