name: infracost
description: Runs infracost to get a cost estimate.
  
inputs:
  working-directory:
    description: Working directory, in which the infracost command is run
    required: true
    default: ${{ runner.temp }}

outputs:
  output:
    description: infracost output (diff)
    value: ${{ steps.this.outputs.output }}
  summary: 
    description: Short summary containing old monthly + new monthly
    value: ${{ steps.this.outputs.summary }}

runs:
  using: composite
  steps: 
    - id: this
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terragrunt show -json ${{ runner.temp }}/plan.tfplan > plan.json
        infracost configure set currency EUR
        infracost diff --path plan.json --format=json >> infracost.json

        # generate normal output from json
        echo "output<<EOF" >> $GITHUB_OUTPUT
        infracost diff --path plan.json --format=diff >> $GITHUB_OUTPUT 
        echo EOF >> $GITHUB_OUTPUT  

        # generate summary from json
        echo "summary=$(jq -r '.projects | .[] | " \(.pastBreakdown.totalMonthlyCost) → \(.breakdown.totalMonthlyCost)"' < infracost.json) €/Month" >> $GITHUB_OUTPUT
        echo EOF >> $GITHUB_OUTPUT
        