name: configure-git
description: Configures git and gh

inputs:
  user_name:
    description: Git user.name
    required: true
  user_email:
    description: Git user.email
    required: true
  gpg_key_id:
    description: Git user.signingKey
    required: true
  gpg_key_pem:
    description: GPG private key (PEM)
    required: true
  github_token:
    description: GitHub auth token
    required: true

runs:
  using: composite
  steps:
    - run: |
        git config user.name "$USER_NAME"
        git config user.email "$USER_EMAIL"

        echo -n "$GPG_KEY_PEM" | gpg --batch --import
        echo -e "5\ny\n" | gpg --command-fd 0 --edit-key "$GPG_KEY_ID" trust

        git config commit.gpgsign true
        git config user.signingkey "$GPG_KEY_ID"

        echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
      env:
        USER_NAME: ${{ inputs.user_name }}
        USER_EMAIL: ${{ inputs.user_email }}
        GPG_KEY_ID: ${{ inputs.gpg_key_id }}
        GPG_KEY_PEM: ${{ inputs.gpg_key_pem }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
