name: configure-git
description: Configures git and gh

inputs:
  user_name:
    description: Git user.name
    default: ''
  user_email:
    description: Git user.email
    default: ''
  gpg_key_id:
    description: Git user.signingKey
    default: ''
  gpg_key_pem:
    description: GPG private key (PEM)
    default: ''
  ssh_key_pem:
    description: SSH private key (PEM)
    default: ''
  github_token:
    description: GitHub auth token
    default: ''

runs:
  using: composite
  steps:
    - run: |

        if [ -z "$USER_NAME$USER_EMAIL$GPG_KEY_ID$GPG_KEY_PEM$SSH_KEY_PEM$GITHUB_TOKEN" ]; then
          echo "ERROR: No git configuration set"
          exit 1
        fi

        test ! -z "$USER_NAME" && git config --global user.name "$USER_NAME"
        test ! -z "$USER_EMAIL" && git config --global user.email "$USER_EMAIL"

        if [ ! -z "$GPG_KEY_ID" -a ! -z "$GPG_KEY_PEM" ]; then
          echo -n "$GPG_KEY_PEM" | gpg --batch --import
          echo -e "5\ny\n" | gpg --command-fd 0 --edit-key "$GPG_KEY_ID" trust
          git config --global commit.gpgsign true
          git config --global user.signingkey "$GPG_KEY_ID"
        fi
        
        if [ ! -z "$SSH_KEY_PEM" ]; then
          mkdir -m 0700 ~/.ssh
          echo "$SSH_KEY_PEM" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
        fi

        test ! -z "$GITHUB_TOKEN" && echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
      env:
        USER_NAME: ${{ inputs.user_name }}
        USER_EMAIL: ${{ inputs.user_email }}
        GPG_KEY_ID: ${{ inputs.gpg_key_id }}
        GPG_KEY_PEM: ${{ inputs.gpg_key_pem }}
        SSH_KEY_PEM: ${{ inputs.ssh_key_pem }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
