name: configure-git
description: Configures Git CLI

inputs:
  user_name:
    description: User name
    default: GitHub Actions
    required: true
  user_email:
    description: User email
    default: actions@users.noreply.github.com
    required: true
  github_token:
    description: GitHub auth token
    required: true

runs:
  using: composite
  steps:
    - run: |
        git config user.name "${{ inputs.user_name }}"
        git config user.email "${{ inputs.user_email }}"
        echo "GITHUB_TOKEN=${{ inputs.github_token }}" >> $GITHUB_ENV
      shell: bash
