name: configure-git
description: Configures git and gh

inputs:
  user-name:
    description: Git user.name
    default: ''
  user-email:
    description: Git user.email
    default: ''
  gpg-key-id:
    description: Git user.signingKey
    default: ''
  gpg-key-pem:
    description: GPG private key (PEM)
    default: ''
  ssh-key-pem:
    description: SSH private key (PEM)
    default: ''
  github-token:
    description: GitHub auth token
    default: ''

runs:
  using: composite
  steps:
    - run: |

        # Fail fast if no config set
        if [ -z "$USER_NAME$USER_EMAIL$GPG_KEY_ID$GPG_KEY_PEM$SSH_KEY_PEM$GITHUB_TOKEN" ]; then
          echo "ERROR: No git configuration set"
          exit 1
        fi

        # Set user identity
        if [ ! -z "$USER_NAME" -a ! -z "$USER_EMAIL" ]; then
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
        fi

        # Setup GPG key
        if [ ! -z "$GPG_KEY_ID" -a ! -z "$GPG_KEY_PEM" ]; then
          echo -n "$GPG_KEY_PEM" | gpg --batch --import
          echo -e "5\ny\n" | gpg --command-fd 0 --edit-key "$GPG_KEY_ID" trust
          git config --global commit.gpgsign true
          git config --global user.signingkey "$GPG_KEY_ID"
        fi
        
        # Setup SSH key
        if [ ! -z "$SSH_KEY_PEM" ]; then
          mkdir -m 0700 ~/.ssh
          echo "$SSH_KEY_PEM" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
        fi
        
        # Setup gh auth
        if [ ! -z "$GITHUB_TOKEN" ]; then
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
        fi
      env:
        USER_NAME: ${{ inputs.user-name }}
        USER_EMAIL: ${{ inputs.user-email }}
        GPG_KEY_ID: ${{ inputs.gpg-key-id }}
        GPG_KEY_PEM: ${{ inputs.gpg-key-pem }}
        SSH_KEY_PEM: ${{ inputs.ssh-key-pem }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
