name: configure-git
description: Configures Git and gh CLIs

inputs:
  user_name:
    description: Git user.name
    required: true
  user_email:
    description: Git user.email
    required: true
  github_token:
    description: GitHub auth token
    required: true

runs:
  using: composite
  steps:
    - run: |
        git config user.name "${{ inputs.user_name }}"
        git config user.email "${{ inputs.user_email }}"
        echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
