name: setup-terragrunt
description: Installs gruntworks' terragrunt

inputs:
  version:
    description: Terragrunt version, e.g. 0.26.2
    required: true

runs:
  using: composite
  steps:
    - id: setup
      shell: bash
      run: |
        echo "PATH: $PATH"
        echo "HOME: $HOME"
        echo "WORKSPACE: $GITHUB_WORKSPACE"
        exit 1
        #url="https://github.com/gruntwork-io/terragrunt/releases/download/v${{ inputs.version }}/terragrunt_linux_amd64"
        #curl -fsSL $url -o ~/.local/bin/terragrunt
        #chmod +x ~/.local/bin/terragrunt
