name: setup-terragrunt
description: Installs gruntworks' terragrunt

inputs:
  version:
    description: Terragrunt version, e.g. 0.26.2
    required: true

runs:
  using: composite
  steps:
    - id: setup
      shell: bash
      run: |
        temp_bin_dir="$(mktemp -d $RUNNER_TEMP/XXXXXXXXXXXXXXXX)"
        url="https://github.com/gruntwork-io/terragrunt/releases/download/v${{ inputs.version }}/terragrunt_linux_amd64"
        curl -fsSL $url -o $temp_bin_dir/terragrunt
        chmod +x $temp_bin_dir/terragrunt
        echo "$temp_bin_dir" >> $GITHUB_PATH
