name: setup-terragrunt
description: Install terragrunt

inputs:
  version:
    description: Terragrunt version
    required: true

runs:
  using: composite
  steps: 
    - id: 
      run: |

        curl -LsS https://github.com/gruntwork-io/terragrunt/releases/download/v${{ inputs.version }}/terragrunt_linux_amd64 /usr/local/bin/terragrunt
        chmod +x /usr/local/bin/terragrunt

      shell: bash

