name: infracost
description: >
  Runs infracost to get a cost estimate.
  
inputs:
  working-directory:
    description: Working directory, in which the infracost command is run
    required: true
    default: ${{ runner.temp }}
  max-output-length:
    description: Maximum output length (combined stdout + stderr), in characters
    required: false
    default: 65000
  on-truncate-message:
    description: Message to append to output, if it gets truncated due to exceeding max length
    required: false
    default: "\n[output truncated, see workflow logs for complete output]"

outputs:
  output:
    description: infracost output (diff)
    value: ${{ steps.this.outputs.output }}
  summary: 
    description: Short summary containing old monthly + new monthly
    value: ${{ steps.this.outputs.summary }}

runs:
  using: composite
  steps: 
    - id: this
      shell: bash
      run: |
     
        terragrunt show -json "{ $working-directory }/plan.tfplan" > "{ $working-directory }/plan.json"
        infracost configure set currency EUR
        infracost diff --path="{ $working-directory }/plan.json" --format=json >> "{ $working-directory }/infracost.json"

        # generate normal output from json
        echo "output<<EOF" >> $GITHUB_OUTPUT
        infracost diff --path="{ $working-directory }/plan.json" --format=diff >> $GITHUB_OUTPUT 
        echo EOF >> $GITHUB_OUTPUT  

        # generate summary from json
        echo "summary=$(jq -r '.projects | .[] | " \(.pastBreakdown.totalMonthlyCost) → \(.breakdown.totalMonthlyCost)"' < "{ $working-directory }/infracost.json") €/Month" >> $GITHUB_OUTPUT
        echo EOF >> $GITHUB_OUTPUT

      working-directory: ${{ inputs.working-directory }}
      env:
        MAX_OUTPUT_LENGTH: ${{ inputs.max-output-length }}
        ON_TRUNCATE_MSG: ${{ inputs.on-truncate-message }}
