name: configure-git
description: Configures Git CLI

inputs:
  user_name:
    description: User name
    default: GitHub Actions
    required: true
  user_email:
    description: User email address
    default: actions@users.noreply.github.com
    required: true

runs:
  using: composite
  steps:
    - run: git config user.name "${{ inputs.user_name }}"
    - run: git config user.email "${{ inputs.user_email }}"
