name: Select terragrunt version to use
description: Like tgenv - check path for .terragrunt-version file and use version specified there. Otherwise return default version.

inputs:
  default-version:
    description: Default version to use. .terragrunt-version can override this.
    default: 0.24.4
    required: true
  working-directory:
    description: Path within repository
    required: true

outputs:
  version:
    description: Terragrunt version to use
    value: ${{ steps.main.outputs.version }}
  checksum:
    description: Terragrunt binary sha256 checksum
    value: ${{ steps.main.outputs.checksum }}

runs:
  using: composite
  steps: 
    - id: main
      run: |
        declare -A checksums=(
          ["0.28.16"]="8c1a9b30402964a5bd9613e0761593ed4cd0b17aa341b50b59dec10fd2e9f87e"
          ["0.27.1"]="b9f174e6613fe84121352ecdd238783504b642d390df87f8f8d760b42c44c02a"
          ["0.24.4"]="f65a22becc185af5291870b04653939cab0cee86beda97fd774feb6dc822b416"
        )

        version="${{ inputs.default-version }}"
        if [ -f .terragrunt-version ]; then
          version=$(cat .terragrunt-version)
        fi

        checksum=${checksums[$version]}
        if [ "${checksum}" == "" ]; then
          echo "Checksum is missing for version ${version}. Check version or update this composite run step action to include new checksum."
          echo "Exiting."
          exit 1
        fi

        echo ::set-output name=version::${version}
        echo ::set-output name=checksum::${checksum}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
